services:
  userapi-mysql:
    image: mysql:8.0
    container_name: userapi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userapi
    ports:
      - "3306:3306"
    volumes:
      - userapi_mysql_data:/var/lib/mysql

  userapi-api:
    build: .
    container_name: userapi-api
    depends_on:
      - userapi-mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://userapi-mysql:3306/userapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  userapi_mysql_data:
